//! Codegen is deliberately dumb (invariant I3): no checking happens here.
//! If a Program reaches this module, emission must always succeed and the
//! resulting Rust must always compile.

use crate::ast::{
    AccessConvention, ConstAttr, Expr, Field, Func, Item, Program, RustConstKind, Stmt,
    StructDef, Type,
};
use crate::syntax;
use std::collections::HashMap;

fn mangle(name: &str) -> String {
    if name == "main" {
        "main".to_string()
    } else {
        format!("user_{}", name)
    }
}

fn rust_type(ty: &Type, ref_lifetime: Option<&str>) -> String {
    match ty {
        Type::Int => "i64".to_string(),
        Type::Float => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::List(inner) => format!("Vec<{}>", rust_type(inner, ref_lifetime)),
        Type::Shared(inner) => format!("std::sync::Arc<{}>", rust_type(inner, ref_lifetime)),
        Type::Named(name) => format!("user_{}", name),
    }
}

fn rust_param_type(convention: AccessConvention, ty: &Type) -> String {
    let base = rust_type(ty, None);
    match convention {
        AccessConvention::Read => format!("&{}", base),
        AccessConvention::Mutate => format!("&mut {}", base),
        AccessConvention::Move => base,
    }
}

fn rust_return_type(ty: &Type, is_view: bool) -> String {
    let base = rust_type(ty, None);
    if is_view {
        format!("&{}", base)
    } else {
        base
    }
}

fn struct_lifetimes(fields: &[Field]) -> Vec<String> {
    let mut labels: Vec<String> = Vec::new();
    for f in fields {
        if !f.is_stored_ref {
            continue;
        }
        let label = f
            .stored_ref_label
            .clone()
            .unwrap_or_else(|| "src".to_string());
        if !labels.contains(&label) {
            labels.push(label);
        }
    }
    labels
}

fn emit_struct(s: &StructDef, out: &mut String) {
    let lifetimes = struct_lifetimes(&s.fields);
    let lt_params = if lifetimes.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            lifetimes
                .iter()
                .map(|l| format!("'{}", l))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    out.push_str(&format!("struct user_{}{} {{\n", s.name, lt_params));
    for f in &s.fields {
        let lt = if f.is_stored_ref {
            let label = f
                .stored_ref_label
                .clone()
                .unwrap_or_else(|| "src".to_string());
            format!("'{}", label)
        } else {
            String::new()
        };
        let field_ty = if f.is_stored_ref {
            format!("&{} {}", lt, rust_type(&f.ty, Some(&lt)))
        } else {
            rust_type(&f.ty, None)
        };
        out.push_str(&format!("    {}: {},\n", mangle(&f.name), field_ty));
    }
    out.push_str("}\n\n");
}

fn emit_const(c: &crate::ast::ConstDef, out: &mut String) {
    let val = emit_expr(&c.value, &HashMap::new());
    let ty = match &c.value {
        Expr::Str(_) => "String",
        Expr::Int(_) => "i64",
        _ => "i64",
    };
    let inline = if c.attrs.contains(&ConstAttr::ForceInline) {
        "#[inline]\n"
    } else {
        ""
    };
    match c.rust_kind {
        RustConstKind::Const => {
            out.push_str(&format!(
                "{}{} {}: {} = {};\n\n",
                inline,
                "const",
                mangle(&c.name).to_uppercase(),
                ty,
                val
            ));
        }
        RustConstKind::Static => {
            out.push_str(&format!(
                "{}static {}: {} = {};\n\n",
                inline,
                mangle(&c.name).to_uppercase(),
                ty,
                val
            ));
        }
    }
}

pub fn emit(prog: &Program) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} — do not edit. Edit the .{} source instead.\n",
        syntax::BINARY_NAME,
        syntax::FILE_EXT
    ));
    out.push_str(&format!(
        "// If rustc rejects this file, that is a bug in {} (invariant I2).\n",
        syntax::BINARY_NAME
    ));
    out.push_str("#![allow(warnings)]\n\n");

    let has_shared = prog.items.iter().any(|item| match item {
        Item::Func(f) => f.params.iter().any(|p| matches!(p.ty, Type::Shared(_)))
            || f.return_type.as_ref().is_some_and(|t| matches!(t, Type::Shared(_))),
        Item::Struct(s) => s.fields.iter().any(|f| matches!(f.ty, Type::Shared(_))),
        _ => false,
    });
    if has_shared {
        out.push_str("use std::sync::Arc;\n\n");
    }

    for item in &prog.items {
        match item {
            Item::Struct(s) => emit_struct(s, &mut out),
            Item::Const(c) => emit_const(c, &mut out),
            Item::Func(_) => {}
        }
    }

    for item in &prog.items {
        if let Item::Func(f) = item {
            emit_func(f, &mut out);
        }
    }
    out
}

fn emit_func(f: &Func, out: &mut String) {
    let ret = f
        .return_type
        .as_ref()
        .map(|t| rust_return_type(t, f.is_view_return))
        .unwrap_or_default();
    let ret_clause = if ret.is_empty() {
        String::new()
    } else {
        format!(" -> {}", ret)
    };
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", mangle(&p.name), rust_param_type(p.convention, &p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "fn {}{}({}){} {{\n",
        mangle(&f.name),
        if f.is_view_return && f.return_type.is_some() {
            // Elided lifetime on view returns — no explicit lifetime param.
            String::new()
        } else {
            String::new()
        },
        params,
        ret_clause
    ));
    let mut locals: HashMap<String, String> = HashMap::new();
    for p in &f.params {
        locals.insert(p.name.clone(), mangle(&p.name));
    }
    for stmt in &f.body {
        emit_stmt(stmt, &mut locals, out, 1);
    }
    out.push_str("}\n\n");
}

fn emit_stmt(stmt: &Stmt, locals: &mut HashMap<String, String>, out: &mut String, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Val(b) => {
            let mut init = emit_expr(&b.init, locals);
            if b.mutable {
                out.push_str(&format!("{}let mut {} = {};\n", pad, mangle(&b.name), init));
            } else {
                out.push_str(&format!("{}let {} = {};\n", pad, mangle(&b.name), init));
            }
            locals.insert(b.name.clone(), mangle(&b.name));
            let _ = &mut init;
        }
        Stmt::Return(expr, _) => {
            out.push_str(&format!("{}return {};\n", pad, emit_expr(expr, locals)));
        }
        Stmt::Loop(inner, _) => {
            out.push_str(&format!("{}loop {{\n", pad));
            emit_stmts(inner, locals, out, indent + 1);
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::Unsafe(inner, _) => {
            out.push_str(&format!("{}unsafe {{\n", pad));
            emit_stmts(inner, locals, out, indent + 1);
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::Call(call) => {
            if call.name == syntax::BUILTIN_PRINT {
                let arg = emit_call_arg(&call.args[0], locals);
                out.push_str(&format!("{}println!(\"{{}}\", {});\n", pad, arg));
            } else {
                let args = call
                    .args
                    .iter()
                    .map(|a| emit_call_arg(a, locals))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("{}{}({});\n", pad, mangle(&call.name), args));
            }
        }
    }
}

fn emit_stmts(stmts: &[Stmt], locals: &mut HashMap<String, String>, out: &mut String, indent: usize) {
    for stmt in stmts {
        emit_stmt(stmt, locals, out, indent);
    }
}

fn emit_call_arg(arg: &crate::ast::CallArg, locals: &HashMap<String, String>) -> String {
    let mut s = emit_expr(&arg.expr, locals);
    if arg.flags.implicit_clone {
        s = format!("{}.clone()", s);
    } else if arg.flags.shared_auto_clone {
        s = format!("Arc::clone(&{})", s);
    }
    match arg.convention {
        AccessConvention::Mutate => format!("&mut {}", s),
        AccessConvention::Move => s,
        AccessConvention::Read => s,
    }
}

fn emit_expr(expr: &Expr, locals: &HashMap<String, String>) -> String {
    match expr {
        Expr::Str(s) => format!("{:?}.to_string()", s),
        Expr::Int(n) => format!("{}i64", n),
        Expr::Ident(name, _) => locals
            .get(name)
            .cloned()
            .unwrap_or_else(|| mangle(name)),
        Expr::Deref(inner, _) => format!("*{}", emit_expr(inner, locals)),
        Expr::Member(inner, member, _) => {
            if member == "clone" {
                format!("{}.clone()", emit_expr(inner, locals))
            } else {
                format!("{}.{}", emit_expr(inner, locals), member)
            }
        }
    }
}
