//! Codegen is deliberately dumb (invariant I3): no checking happens here.
//! If a Program reaches this module, emission must always succeed and the
//! resulting Rust must always compile.
//!
//! Type-alignment rules (so emitted Rust always typechecks):
//!   - scalar params (Int/Float/Bool) pass by value, String by `&String`;
//!     `mut` params are `&mut T`; `take` params are `T` by value
//!   - a name bound to a `&T`/`&mut T` parameter is always emitted as the
//!     place `(*user_x)`, so every name has its plain Lex type
//!   - every printed/interpolated value goes through the `LexShow` trait
//!     in the prelude (Float keeps its decimal part there, S21)
//!   - every operator result is fully parenthesized

use crate::ast::{
    AccessConvention, ConstAttr, ElseBranch, Expr, Field, Func, IfStmt, Item, Program,
    RustConstKind, Stmt, StrPart, StructDef, Type, UnOp,
};
use crate::syntax;
use std::collections::HashMap;

/// Emitted at the top of every program: one tiny display trait so codegen
/// never needs to know a value's type to print it. Monomorphized by rustc;
/// zero runtime dispatch. Float printing keeps the decimal part (S21).
const PRELUDE: &str = r#"trait LexShow { fn lex_show(&self) -> String; }
impl LexShow for i64 { fn lex_show(&self) -> String { self.to_string() } }
impl LexShow for f64 { fn lex_show(&self) -> String { format!("{:?}", self) } }
impl LexShow for bool { fn lex_show(&self) -> String { self.to_string() } }
impl LexShow for String { fn lex_show(&self) -> String { self.clone() } }
impl<T: LexShow> LexShow for &T { fn lex_show(&self) -> String { (**self).lex_show() } }
"#;

fn mangle(name: &str) -> String {
    if name == "main" {
        "main".to_string()
    } else {
        format!("user_{}", name)
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int => "i64".to_string(),
        Type::Float => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::List(inner) => format!("Vec<{}>", rust_type(inner)),
        Type::Shared(inner) => format!("std::sync::Arc<{}>", rust_type(inner)),
        Type::Named(name) => format!("user_{}", name),
    }
}

fn rust_param_type(convention: AccessConvention, ty: &Type) -> String {
    let base = rust_type(ty);
    match convention {
        AccessConvention::Read if ty.is_scalar() => base,
        AccessConvention::Read => format!("&{}", base),
        AccessConvention::Mutate => format!("&mut {}", base),
        AccessConvention::Move => base,
    }
}

fn rust_return_type(ty: &Type, is_view: bool) -> String {
    let base = rust_type(ty);
    if is_view {
        format!("&{}", base)
    } else {
        base
    }
}

/// What a Lex name looks like in Rust expression position.
#[derive(Clone)]
struct Slot {
    rust_name: String,
    /// The Rust binding is a reference; emit `(*name)` to get the value.
    deref: bool,
}

struct Cx {
    /// callee name -> parameter conventions+types (for call-site emission).
    sigs: HashMap<String, Vec<(AccessConvention, Type)>>,
    consts: HashMap<String, String>,
}

pub fn emit(prog: &Program) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by {} — do not edit. Edit the .{} source instead.\n",
        syntax::BINARY_NAME,
        syntax::FILE_EXT
    ));
    out.push_str(&format!(
        "// If rustc rejects this file, that is a bug in {} (invariant I2).\n",
        syntax::BINARY_NAME
    ));
    out.push_str("#![allow(warnings)]\n\n");
    out.push_str(PRELUDE);
    out.push('\n');

    let mut cx = Cx {
        sigs: HashMap::new(),
        consts: HashMap::new(),
    };
    for item in &prog.items {
        match item {
            Item::Func(f) => {
                cx.sigs.insert(
                    f.name.clone(),
                    f.params
                        .iter()
                        .map(|p| (p.convention, p.ty.clone()))
                        .collect(),
                );
            }
            Item::Const(c) => {
                cx.consts
                    .insert(c.name.clone(), mangle(&c.name).to_uppercase());
            }
            Item::Struct(_) => {}
        }
    }

    for item in &prog.items {
        match item {
            Item::Struct(s) => emit_struct(s, &mut out),
            Item::Const(c) => emit_const(c, &mut out),
            Item::Func(_) => {}
        }
    }

    for item in &prog.items {
        if let Item::Func(f) = item {
            emit_func(&cx, f, &mut out);
        }
    }
    out
}

fn struct_lifetimes(fields: &[Field]) -> Vec<String> {
    let mut labels: Vec<String> = Vec::new();
    for f in fields {
        if !f.is_stored_ref {
            continue;
        }
        let label = f
            .stored_ref_label
            .clone()
            .unwrap_or_else(|| "src".to_string());
        if !labels.contains(&label) {
            labels.push(label);
        }
    }
    labels
}

fn emit_struct(s: &StructDef, out: &mut String) {
    let lifetimes = struct_lifetimes(&s.fields);
    let lt_params = if lifetimes.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            lifetimes
                .iter()
                .map(|l| format!("'{}", l))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    out.push_str(&format!("struct user_{}{} {{\n", s.name, lt_params));
    for f in &s.fields {
        let field_ty = if f.is_stored_ref {
            let label = f
                .stored_ref_label
                .clone()
                .unwrap_or_else(|| "src".to_string());
            format!("&'{} {}", label, rust_type(&f.ty))
        } else {
            rust_type(&f.ty)
        };
        out.push_str(&format!("    {}: {},\n", mangle(&f.name), field_ty));
    }
    out.push_str("}\n\n");
}

fn emit_const(c: &crate::ast::ConstDef, out: &mut String) {
    let (val, ty) = match &c.value {
        Expr::Int(n, _) => (format!("{}i64", n), "i64"),
        Expr::Float(v, _) => (format!("{:?}f64", v), "f64"),
        Expr::Bool(b, _) => (b.to_string(), "bool"),
        // sema rejects anything else; keep emission total anyway.
        _ => ("0i64".to_string(), "i64"),
    };
    let inline = if c.attrs.contains(&ConstAttr::ForceInline) {
        "#[inline]\n"
    } else {
        ""
    };
    let kw = match c.rust_kind {
        RustConstKind::Const => "const",
        RustConstKind::Static => "static",
    };
    out.push_str(&format!(
        "{}{} {}: {} = {};\n\n",
        inline,
        kw,
        mangle(&c.name).to_uppercase(),
        ty,
        val
    ));
}

fn emit_func(cx: &Cx, f: &Func, out: &mut String) {
    let ret = f
        .return_type
        .as_ref()
        .map(|t| rust_return_type(t, f.is_view_return))
        .unwrap_or_default();
    let ret_clause = if ret.is_empty() {
        String::new()
    } else {
        format!(" -> {}", ret)
    };
    let params = f
        .params
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                mangle(&p.name),
                rust_param_type(p.convention, &p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "fn {}({}){} {{\n",
        mangle(&f.name),
        params,
        ret_clause
    ));
    let mut env: HashMap<String, Slot> = HashMap::new();
    for p in &f.params {
        let deref = match p.convention {
            AccessConvention::Read => !p.ty.is_scalar(),
            AccessConvention::Mutate => true,
            AccessConvention::Move => false,
        };
        env.insert(
            p.name.clone(),
            Slot {
                rust_name: mangle(&p.name),
                deref,
            },
        );
    }
    emit_stmts(cx, &f.body, &mut env, out, 1, f.is_view_return);
    out.push_str("}\n\n");
}

fn emit_stmts(
    cx: &Cx,
    stmts: &[Stmt],
    env: &mut HashMap<String, Slot>,
    out: &mut String,
    indent: usize,
    view_return: bool,
) {
    for stmt in stmts {
        emit_stmt(cx, stmt, env, out, indent, view_return);
    }
}

fn emit_stmt(
    cx: &Cx,
    stmt: &Stmt,
    env: &mut HashMap<String, Slot>,
    out: &mut String,
    indent: usize,
    view_return: bool,
) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Val(b) => {
            let init = emit_expr(cx, &b.init, env);
            let kw = if b.mutable { "let mut" } else { "let" };
            out.push_str(&format!("{}{} {} = {};\n", pad, kw, mangle(&b.name), init));
            env.insert(
                b.name.clone(),
                Slot {
                    rust_name: mangle(&b.name),
                    deref: false,
                },
            );
        }
        Stmt::Assign {
            name, op, value, ..
        } => {
            let place = place_of(env, name);
            let v = emit_expr(cx, value, env);
            match op {
                Some(op) => out.push_str(&format!(
                    "{}{} {}= {};\n",
                    pad,
                    place,
                    op.spell(),
                    v
                )),
                None => out.push_str(&format!("{}{} = {};\n", pad, place, v)),
            }
        }
        Stmt::Expr(e) => {
            out.push_str(&format!("{}{};\n", pad, emit_expr_stmt(cx, e, env)));
        }
        Stmt::Return(Some(e), _) => {
            let val = if view_return {
                emit_view_return(cx, e, env)
            } else {
                emit_expr(cx, e, env)
            };
            out.push_str(&format!("{}return {};\n", pad, val));
        }
        Stmt::Return(None, _) => {
            out.push_str(&format!("{}return;\n", pad));
        }
        Stmt::If(ifs) => emit_if(cx, ifs, env, out, indent, view_return),
        Stmt::While { cond, body, .. } => {
            out.push_str(&format!("{}while {} {{\n", pad, emit_expr(cx, cond, env)));
            emit_stmts(cx, body, env, out, indent + 1, view_return);
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::For {
            var,
            start,
            end,
            body,
            ..
        } => {
            // S22: both ends included -> Rust `..=`.
            let s = emit_expr(cx, start, env);
            let e = emit_expr(cx, end, env);
            out.push_str(&format!(
                "{}for {} in ({})..=({}) {{\n",
                pad,
                mangle(var),
                s,
                e
            ));
            let prev = env.insert(
                var.clone(),
                Slot {
                    rust_name: mangle(var),
                    deref: false,
                },
            );
            emit_stmts(cx, body, env, out, indent + 1, view_return);
            match prev {
                Some(p) => {
                    env.insert(var.clone(), p);
                }
                None => {
                    env.remove(var);
                }
            }
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::Switch {
            subject,
            arms,
            else_body,
            ..
        } => {
            // S24: evaluate the subject once, then run the first true arm.
            out.push_str(&format!("{}{{\n", pad));
            let inner_pad = "    ".repeat(indent + 1);
            out.push_str(&format!(
                "{}let _lex_switch_subject = &({});\n",
                inner_pad,
                emit_expr(cx, subject, env)
            ));
            for (i, arm) in arms.iter().enumerate() {
                let kw = if i == 0 { "if" } else { "} else if" };
                out.push_str(&format!(
                    "{}{} {} {{\n",
                    inner_pad,
                    kw,
                    emit_expr(cx, &arm.cond, env)
                ));
                emit_stmts(cx, &arm.body, env, out, indent + 2, view_return);
            }
            if arms.is_empty() {
                emit_stmts(cx, else_body, env, out, indent + 1, view_return);
            } else {
                out.push_str(&format!("{}}} else {{\n", inner_pad));
                emit_stmts(cx, else_body, env, out, indent + 2, view_return);
                out.push_str(&format!("{}}}\n", inner_pad));
            }
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::Break(_) => out.push_str(&format!("{}break;\n", pad)),
        Stmt::Continue(_) => out.push_str(&format!("{}continue;\n", pad)),
        Stmt::Loop(inner, _) => {
            out.push_str(&format!("{}loop {{\n", pad));
            emit_stmts(cx, inner, env, out, indent + 1, view_return);
            out.push_str(&format!("{}}}\n", pad));
        }
        Stmt::Unsafe(inner, _) => {
            out.push_str(&format!("{}unsafe {{\n", pad));
            emit_stmts(cx, inner, env, out, indent + 1, view_return);
            out.push_str(&format!("{}}}\n", pad));
        }
    }
}

/// `-> view T` returns a reference; emit `&place` or the existing borrow.
fn emit_view_return(cx: &Cx, e: &Expr, env: &HashMap<String, Slot>) -> String {
    match e {
        Expr::Ident(name, _) => {
            if let Some(c) = cx.consts.get(name) {
                return format!("&{}", c);
            }
            if let Some(slot) = env.get(name) {
                if slot.deref {
                    return slot.rust_name.clone();
                }
                return format!("&{}", slot.rust_name);
            }
            place_of(env, name)
        }
        _ => emit_expr(cx, e, env),
    }
}

fn emit_if(
    cx: &Cx,
    ifs: &IfStmt,
    env: &mut HashMap<String, Slot>,
    out: &mut String,
    indent: usize,
    view_return: bool,
) {
    let pad = "    ".repeat(indent);
    out.push_str(&format!("{}if {} {{\n", pad, emit_expr(cx, &ifs.cond, env)));
    emit_stmts(cx, &ifs.then_body, env, out, indent + 1, view_return);
    match &ifs.else_branch {
        None => out.push_str(&format!("{}}}\n", pad)),
        Some(ElseBranch::Else(body)) => {
            out.push_str(&format!("{}}} else {{\n", pad));
            emit_stmts(cx, body, env, out, indent + 1, view_return);
            out.push_str(&format!("{}}}\n", pad));
        }
        Some(ElseBranch::ElseIf(next)) => {
            out.push_str(&format!("{}}} else ", pad));
            // Re-emit the nested if at column 0 of this line.
            let mut nested = String::new();
            emit_if(cx, next, env, &mut nested, indent, view_return);
            // Trim the pad the nested emit added so it joins `else `.
            let trimmed = nested.trim_start_matches(&pad).to_string();
            out.push_str(&trimmed);
        }
    }
}

fn place_of(env: &HashMap<String, Slot>, name: &str) -> String {
    match env.get(name) {
        Some(slot) if slot.deref => format!("(*{})", slot.rust_name),
        Some(slot) => slot.rust_name.clone(),
        None => mangle(name),
    }
}

/// A call in statement position.
fn emit_expr_stmt(cx: &Cx, e: &Expr, env: &HashMap<String, Slot>) -> String {
    emit_expr(cx, e, env)
}

fn emit_expr(cx: &Cx, e: &Expr, env: &HashMap<String, Slot>) -> String {
    match e {
        Expr::Int(n, _) => format!("{}i64", n),
        Expr::Float(v, _) => format!("{:?}f64", v),
        Expr::Bool(b, _) => b.to_string(),
        Expr::Str(parts, _) => emit_str(cx, parts, env),
        Expr::Ident(name, _) => {
            if let Some(c) = cx.consts.get(name) {
                return c.clone();
            }
            place_of(env, name)
        }
        Expr::Unary(op, inner, _) => {
            let i = emit_expr(cx, inner, env);
            match op {
                UnOp::Neg => format!("(-({}))", i),
                UnOp::Not => format!("(!({}))", i),
            }
        }
        Expr::Binary(op, l, r, _) => {
            let ls = emit_expr(cx, l, env);
            let rs = emit_expr(cx, r, env);
            format!("(({}) {} ({}))", ls, op.spell(), rs)
        }
        Expr::Call(call) => emit_call(cx, call, env),
        Expr::Deref(inner, _) => format!("*{}", emit_expr(cx, inner, env)),
        Expr::Member(inner, member, _) => {
            // Only `.clone()` reaches codegen before M3 (sema enforces).
            format!("({}).{}()", emit_expr(cx, inner, env), member)
        }
    }
}

/// String literal with interpolation: build the String piece by piece —
/// no format-string escaping pitfalls (S8/S20).
fn emit_str(cx: &Cx, parts: &[StrPart], env: &HashMap<String, Slot>) -> String {
    if parts.len() == 1 {
        if let StrPart::Lit(s) = &parts[0] {
            return format!("{:?}.to_string()", s);
        }
    }
    let mut body = String::from("{ let mut _lex_s = String::new(); ");
    for p in parts {
        match p {
            StrPart::Lit(s) => {
                if !s.is_empty() {
                    body.push_str(&format!("_lex_s.push_str({:?}); ", s));
                }
            }
            StrPart::Interp(e) => {
                body.push_str(&format!(
                    "_lex_s.push_str(&({}).lex_show()); ",
                    emit_expr(cx, e, env)
                ));
            }
        }
    }
    body.push_str("_lex_s }");
    body
}

fn emit_call(cx: &Cx, call: &crate::ast::Call, env: &HashMap<String, Slot>) -> String {
    if call.name == syntax::BUILTIN_PRINT {
        let arg = emit_expr(cx, &call.args[0].expr, env);
        return format!("println!(\"{{}}\", ({}).lex_show())", arg);
    }
    let sig = cx.sigs.get(&call.name);
    let args = call
        .args
        .iter()
        .enumerate()
        .map(|(i, a)| {
            let mut s = emit_expr(cx, &a.expr, env);
            if a.flags.implicit_clone {
                s = format!("({}).clone()", s);
            } else if a.flags.shared_auto_clone {
                s = format!("std::sync::Arc::clone(&{})", s);
            }
            let conv = sig
                .and_then(|ps| ps.get(i))
                .map(|(c, t)| (*c, t.clone()));
            match conv {
                Some((AccessConvention::Read, t)) if !t.is_scalar() => format!("&({})", s),
                Some((AccessConvention::Mutate, _)) => format!("&mut ({})", s),
                _ => s,
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("{}({})", mangle(&call.name), args)
}
